import React from 'react'

const HelpOrderEntry = () => {
  return (
    <div className="help-content">
      <h1 className="text-left">
        OrderPoints - Order Entry
      </h1>
      <p className="text-left">
        Order Entry in OrderPoints allows users to create a new order directly within eFactory by entering the necessary order details.  
        It is the default view for the OrderPoints 
        tab. 
      </p>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;</p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left"></p>
          <h4 className="text-left">
            Order Header
          </h4>
          <p className="text-left">
            Order Entry starts with the Order Header section. 
            <br/><br/>
            The field definitions are listed below.
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-right">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/orderPoints - OrderEntry2.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <table className="table table-bordered">
        <tbody>
          <tr className="active">
            <td> # </td>
            <td> Field </td>
            <td> Description </td>
          </tr>
          <tr>
            <td> 1 </td>
            <td> <strong>Account # - Warehouse </strong></td>
            <td> <p className="text-left">Click the dropdown to select the account and warehouse from which the shipment should be made</p></td>
          </tr>
          <tr>
            <td> 2 </td>
            <td><strong>Order #</strong></td>
            <td>
              <p className="text-left">
                The order number is autogenerated - This is indicated with a green background color. It can also be keyed in. <br/> This preference can be changed via Settings-&gt;General Settings
              </p>
              <p className="text-left"></p>
            </td>
          </tr>
          <tr>
            <td> 3 </td>
            <td><strong>Customer #</strong></td>
            <td>
              <p className="text-left">
                The customer number is an optional field for entering a customer number when applicable.
              </p>
              <p className="text-left"></p>
            </td>
          </tr> 
          <tr>
            <td> 4 </td>
            <td><strong>PO #</strong></td>
            <td> 
              <p className="text-left">
                The purchase order number is an optional field for entering a purchase order number when applicable.
              </p>
              <p className="text-left"></p>
            </td>
          </tr> 
          <tr>
            <td> 5 </td>
            <td><strong>Order Status</strong></td>
            <td>
              <p className="text-left">
                Select the status for the order: On Hold, Normal or Rush.
              </p>
              <p className="text-left"></p>
            </td>
          </tr>  
          <tr>
            <td> 6 </td>
            <td><strong>PO Date</strong></td>
            <td>
              <p className="text-left">
                The purchase order date will default to today's 
                date.  It can be set to a future date, 
                but cannot be blank or a past date.
              </p>
              <p className="text-left"></p>
            </td>
          </tr>  
          <tr>
            <td> 7 </td>
            <td> <strong>Shipping Instructions </strong></td>
            <td> 
              <p className="text-left">
                Shipping instructions will be seen by the operation 
                and shipping teams.  It is not printed on the packing 
                slip.
              </p>
            </td>
          </tr>
          <tr>
            <td> 8 </td>
            <td><strong>Comments</strong></td>
            <td>
              <p className="text-left">
                Comments are for the customer and will appear on the 
                packing slip.
              </p>
            </td>
          </tr>
        </tbody>
      </table>
      <div className="row">
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Shipping Address 
          </h4>
          <p className="text-left">
            Type in the first few characters in the Company Name and 
            press "Enter" - If the entry is found in the address book, 
            it will automatically populate the address fields.
            <br/><br/>
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/orderPoints - required-field.png"/> indicates
             a required field.
            <br/><br/>
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-right">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/orderPoints - shipping-address.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Address Book
          </h4>
          <p className="text-left">
            If there are multiple entries, it will bring up the address 
            book for you to select the correct entry.
            <br/><br/>
            The same window will show up if the "ADDRESS BOOK" link is 
            selected.
            <br/><br/>
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-right">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_AddressBook2.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Items 
          </h4>
          <p className="text-left">
            Type in the first few characters in the Item Name and press 
            "Enter" - This brings up a pop window
            <br/>
            The same window will show up if "Browse Items" is clicked
            <br/><br/>
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-right">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_ItemSelectionPopup2.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Select Items 
          </h4>
          <p className="text-left">
            Select items, quantity and optionally specify cost per 
            quantity on this screen
            <br/><br/>
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-right">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/orderPoints - ItemBrowse.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Edit Item 
          </h4>
          
          <p className="text-left">
            Each column can be invidiually edited such as Price. 
            <br/>
            More details about the Item can be entered by clicking 
            on the blue arrow.
            <br/><br/>
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-right">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints-ItemEdit.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Shipping
          </h4>
          <p className="text-left">
            Shipping options can be set using the shipping section. 
            Select "EDIT" to edit the fields as needed. 
            <br/><br/>
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_SettingsShipping3.jpg" />
            <br/><br/>
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-center">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_EditSettingsShipping.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>   
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Billing Address
          </h4>
          <p className="text-left">
            Billing address options can be set using the billing address 
            section. Select "EDIT" to edit the fields as needed. 
            <br/><br/>
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_EditBillingAddress2.jpg" />
            <br/><br/>
            In edit mode, select "COPY SHIPPING ADDRESS" to use the 
            shipping address.
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-center">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_EditBillingAddress.jpg"/>
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <p className="text-left">
            &nbsp;
          </p>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4">
          <p className="text-left">
          </p>
          <h4 className="text-left">
            Edit Amounts and Extra Fields
          </h4>
          <p className="text-left">
            Amount fields can be edited by selecting on the "Edit" link. 
            Amount fields are not linked to the item amounts; however, 
            they can be edited for the purpose of printing these details on 
            the packing list. 
            <br/><br/>
            These are independent fields that are used for the packing 
            slip only. The system does not use it for anything other than 
            inclusion in the packing list.
            <br/><br/>
            Extra fields can be used for adding custom information, which 
            can also be edited to be included as information in the packaging 
            slip for shipment.
            <br/><br/>
            Extra fields are defined in the custom field section of the 
            OrderPoints settings. 
            <br/><br/>
          </p>
        </div>
        <div className="col-md-8">
          <p className="text-center">
            <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_EditAmounts2.jpg"/>
          </p>
        </div>
        <div className="row">
          <div className="col-md-12">
            <p className="text-left">
              &nbsp;
            </p>
          </div>
        </div>
        <div className="row">
          <div className="col-md-4">
            <p className="text-left">
            </p>
            <h4 className="text-left">
              Place Order
            </h4>
            <p className="text-left">
              After the required information has been entered, the order 
              can be saved for editing later by clicking on "SAVE DRAFT" 
              button OR the order can be placed by clicking on "PLACE ORDER".
              <br/><br/>
            </p>
          </div>
          <br/>
          <div className="col-md-8">
            <p className="text-center">
              <img role="presentation" src="/src/styles/images/help/op/orderEntry/OrderPoints_saveorderbtn.jpg"/>
            </p>
          </div>
        </div>
        <div className="row">
          <div className="col-md-12">
            <p className="text-left">
              &nbsp;
            </p>
          </div>
        </div>  
      </div>
    </div>
  )
}

export default React.memo(HelpOrderEntry)