import {getUserData}                        from '../../../../util/storageHelperFuncs'

const createRouteAppIdsConfig = () => {
    return {
        '/overview' : 1,
        '/overview/customize-view' : 1,
        '/announcements' : 2,
        '/overview/notes' : 3,

        '/orders/open' : 5,
        '/orders/onhold' : 6,
        '/orders/backorders' : 7,
        '/orders/prerelease' : 8,
        '/orders/shipped' : 9,
        '/orders/canceled' : 10,
        '/orders/all' : 11,

        '/order-lines/open' : 12,
        '/order-lines/onhold' : 13,
        '/order-lines/backorders' : 14,
        '/order-lines/prerelease' : 15,
        '/order-lines/shipped' : 16,
        '/order-lines/canceled' : 17,
        '/order-lines/all' : 18,

        '/order-items/backlog' : 19,
        '/order-items/shipped' : 20,
        '/order-items/all' : 61,

        '/detail/freight' : 21,
        '/detail/package' : 22,
        '/detail/serial' : 23,

        '/analytics/profiles/domestic' : 42,
        '/analytics/profiles/international' : 43,
        '/analytics/slas/shipment-times' : 46,
        '/analytics/slas/rma-receive-times' : 63,
        '/analytics/slas/cyclecount' : 70,
        '/analytics/slas/incident-reports' : 208,
        '/analytics/planning/replenishment' : 44,
        '/analytics/planning/slowmoving' : 45,
        '/analytics/scheduler' : 64,
        '/analytics/scheduler/reports' : 35,
        '/analytics/scheduler/customreports' : 71,

        '/analytics/profiles/time' : 201,
        '/analytics/profiles/customer' : 202,
        '/analytics/profiles/item' : 203,
        '/analytics/profiles/shipservice' : 204,
        '/analytics/profiles/channel' : 205,
        '/analytics/deliverytimes' : 211,

        '/transportation/analyzer' : 207,
        '/transportation/time' : 209,
        '/transportation/service' : 210,

        '/transportation/packages/shipping-detail' : 212,
        '/transportation/packages/cost-estimator' : 213,

        '/orders/documents/bill' : 72,
        '/orders/documents/etags' : 72,
        '/orders/documents/routing' : 72,
        '/orders/documents/reference' : 72,

        '/inventory/items/status' : 26,
        //'/inventory/items/received' : 27,
        '/inventory/items/receiving' : 27,
        '/inventory/items/onhold' : 28,
        '/inventory/items/transactions' : 29,
        //'/inventory/items/toreceive' : 30,
        '/inventory/items/lotmaster' : 31,
        '/inventory/items/asofadate' : 32,
        '/inventory/items/trsummary' : 33,
        '/inventory/items/cyclecount': 34,
        '/inventory/items/dg-data': 39,
        '/inventory/items/bundle' : 206,

        '/inventory/receipts/po-notifications' : 36,
        '/inventory/receipts/po-receipt' : 37,
        '/inventory/receipts/rma-receipt' : 38,

        '/inventory/assembly' : 40,
        '/inventory/returns' : 41,

        '/inventory/documents' : 73, // all 73
        '/inventory/documents/assembly' : 73,
        '/inventory/documents/labels' : 73,
        '/inventory/documents/consigned' : 73,
        '/inventory/documents/return' : 73,
        '/inventory/documents/serial' : 73,
        '/inventory/documents/reference' : 73,

        '/orderpoints' : 47,
        '/orderpoints/new-order' : 47,
        '/orderpoints/drafts' : 48,
        '/orderpoints/addressbook' : 49,
        '/orderpoints/massupload' : 50,
        '/orderpoints/ftp-batches' : 76,
        '/orderpoints/shippingcost' : 51,
        '/orderpoints/documents/reference' : 74,
        '/orderpoints/documents/ftp-folders-send' : 74,
        '/orderpoints/documents/ftp-folders-get' : 74,
        '/orderpoints/help/1' : 53,
        '/orderpoints/help/2' : 53,
        '/orderpoints/help/3' : 53,
        '/orderpoints/help/4' : 53,
        '/orderpoints/help/5' : 53,

        '/returntrak' : 55,
        '/returntrak/drafts' : 56,
        '/returntrak/shipped-orders' : 54,
        '/returntrak/rmas/open' : 57,
        '/returntrak/rmas/all' : 58,
        '/returntrak/rmas/items' : 59,

        '/returntrak/documents' : 75, // all 75
        '/returntrak/documents/return' : 75,
        '/returntrak/documents/reference' : 75,

        '/edi/overview' : 52,
        '/edi/overview/customize-view' : 52,
        '/edi/form' : 99991, // HIDDEN
        '/edi/documents/orders-to-resolve' : 82,
        '/edi/documents/orders-to-approve' : 83,
        '/edi/documents/orders-to-ship' : 84,
        '/edi/documents/order-history' : 85,
        '/edi/documents/asn-856' : 86,
        '/edi/documents/invoice-810' : 87,
        '/edi/documents/remittance-820' : 88,
        '/edi/documents/product-activity-852' : 89,
        '/edi/documents/planning-schedule-830' : 90,
        '/edi/trading-partners/tp-activity' : 91,
        '/edi/trading-partners/tp-items' : 92,
        '/edi/trading-partners/tp-addresses' : 93,
        '/edi/trading-partners/tp-d-ship-methods' : 94,
        '/edi/trading-partners/tp-status' : 95,
        '/edi/trading-partners/basic-profile' : 96,
        '/edi/trading-partners/invoicing-profile' : 97,
        '/edi/trading-partners/dcl-partners' : 98,
        '/edi/ext-shipments/shipment-entry': 99,
        '/edi/ext-shipments/drafts': 100,

        '/documents' : 62,
        '/documents/general/approvals' : 62,
        '/documents/general/assembly' : 62,
        '/documents/general/bill' : 62,
        '/documents/general/consigned' : 62,
        '/documents/general/dangerousgoods' : 62,
        '/documents/general/general' : 62,
        '/documents/general/labels' : 62,
        '/documents/general/purchase' : 62,
        '/documents/general/etags' : 62,
        '/documents/general/return' : 62,
        '/documents/general/routing' : 62,
        '/documents/general/serial' : 62,
        '/documents/reference' : 62,

        '/special-docs/token-incoming-po' : getUserData('policy_code') === 'SYM' ? 62 : -1000,
        '/special-docs/token-incoming-sn' : getUserData('policy_code') === 'SYM' ? 62 : -1000,
        '/special-docs/token-sn-binding' : getUserData('policy_code') === 'SYM' ? 62 : -1000,
        '/special-docs/token-sn-unbinding' : getUserData('policy_code') === 'SYM' ? 62 : -1000,
        '/special-docs/token-cycle-count-info' : getUserData('policy_code') === 'SYM' ? 62 : -1000,

        '/ftp-folders/send' : 62,
        '/ftp-folders/get' : 62,

        '/services/administration-tasks/accounts' : 67,
        '/services/administration-tasks/orderpoints-settings' : 65,
        '/services/administration-tasks/returntrak-settings' : 66,
        '/services/administration-tasks/special-settings' : 99992,

        '/services/administration-tasks/email-notifications/ship-confirmation' : 77,
        '/services/administration-tasks/email-notifications/order-receipt' : 78,
        '/services/administration-tasks/email-notifications/po-receipt' : 79,
        '/services/administration-tasks/email-notifications/rma-receipt' : 80,
        '/services/administration-tasks/email-notifications/unplanned-receipt' : 81,

        '/services/administration-tasks/invoices/open' : 68,
        '/services/administration-tasks/invoices/all' : 69,
        '/services/administration-tasks/invoices/freight-charges' : 214,
        '/services/administration-tasks/invoices/rate-cards' : 214,
    }
}

export default createRouteAppIdsConfig
