import React from 'react'
import * as Sidebars from './index'

const sidebarsConfig = {
  '/overview' : Sidebars['Overview'],
  '/overview/customize-view' : Sidebars['Overview'],
  '/announcements' : Sidebars['Overview'],
  '/overview/notes' : Sidebars['Overview'],
  '/orders/open' : Sidebars['Orders'],
  '/orders/onhold' : Sidebars['Orders'],
  '/orders/backorders' : Sidebars['Orders'],
  '/orders/prerelease' : Sidebars['Orders'],
  '/orders/shipped' : Sidebars['Orders'],
  '/orders/canceled' : Sidebars['Orders'],
  '/orders/all' : Sidebars['Orders'],
  '/order-lines/open' : Sidebars['Orders'],
  '/order-lines/onhold' : Sidebars['Orders'],
  '/order-lines/backorders' : Sidebars['Orders'],
  '/order-lines/prerelease' : Sidebars['Orders'],
  '/order-lines/shipped' : Sidebars['Orders'],
  '/order-lines/canceled' : Sidebars['Orders'],
  '/order-lines/all' : Sidebars['Orders'],
  '/order-items/backlog' : Sidebars['Orders'],
  '/order-items/shipped' : Sidebars['Orders'],
  '/order-items/all' : Sidebars['Orders'],
  '/detail/freight' : Sidebars['Orders'],
  '/detail/package' : Sidebars['Orders'],
  '/detail/serial' : Sidebars['Orders'],
  '/orders/documents/bill' : Sidebars['Orders'],
  '/orders/documents/etags' : Sidebars['Orders'],
  '/orders/documents/routing' : Sidebars['Orders'],
  '/orders/documents/reference' : Sidebars['Orders'],

  '/analytics/profiles/domestic' : Sidebars['Analytics'],
  '/analytics/profiles/international' : Sidebars['Analytics'],
  '/analytics/profiles/time': Sidebars['Analytics'],
  '/analytics/profiles/item': Sidebars['Analytics'],
  '/analytics/profiles/customer': Sidebars['Analytics'],
  '/analytics/profiles/shipservice': Sidebars['Analytics'],
  '/analytics/profiles/channel': Sidebars['Analytics'],
  '/analytics/slas/shipment-times' : Sidebars['Analytics'],
  '/analytics/slas/rma-receive-times' : Sidebars['Analytics'],
  '/analytics/slas/cyclecount' : Sidebars['Analytics'],
  '/analytics/planning/replenishment' : Sidebars['Analytics'],
  '/analytics/planning/slowmoving' : Sidebars['Analytics'],
  '/analytics/scheduler' : Sidebars['Analytics'],
  '/analytics/scheduler/reports' : Sidebars['Analytics'],
  '/analytics/scheduler/customreports' : Sidebars['Analytics'],
  '/analytics/slas/incident-reports' : Sidebars['Analytics'],
  '/analytics/deliverytimes': Sidebars['Analytics'],

  '/inventory/items/status' : Sidebars['Items'],
  '/inventory/items/receiving' : Sidebars['Items'],
  '/inventory/items/onhold' : Sidebars['Items'],
  '/inventory/items/transactions' : Sidebars['Items'],
  '/inventory/items/bundle' : Sidebars['Items'],
  '/inventory/items/toreceive' : Sidebars['Items'],
  '/inventory/items/lotmaster' : Sidebars['Items'],
  '/inventory/items/asofadate' : Sidebars['Items'],
  '/inventory/items/trsummary' : Sidebars['Items'],
  '/inventory/items/cyclecount': Sidebars['Items'],
  '/inventory/items/dg-data': Sidebars['Items'],
  '/inventory/receipts/po-notifications' : Sidebars['Items'],
  '/inventory/receipts/po-receipt' : Sidebars['Items'],
  '/inventory/receipts/rma-receipt' : Sidebars['Items'],
  '/inventory/assembly' : Sidebars['Items'],
  '/inventory/returns' : Sidebars['Items'],
  '/inventory/documents' : Sidebars['Items'], // all 73
  '/inventory/documents/general/dangerousgoods': Sidebars['Items'],
  '/inventory/documents/assembly' : Sidebars['Items'],
  '/inventory/documents/labels' : Sidebars['Items'],
  '/inventory/documents/consigned' : Sidebars['Items'],
  '/inventory/documents/return' : Sidebars['Items'],
  '/inventory/documents/serial' : Sidebars['Items'],
  '/inventory/documents/reference' : Sidebars['Items'],

  '/orderpoints' : Sidebars['OrderPoints'],
  '/orderpoints/new-order' : Sidebars['OrderPoints'],
  '/orderpoints/drafts' : Sidebars['OrderPoints'],
  '/orderpoints/addressbook' : Sidebars['OrderPoints'],
  '/orderpoints/addressbook/edit' : Sidebars['OrderPoints'],
  '/orderpoints/addressbook/add' : Sidebars['OrderPoints'],
  '/orderpoints/massupload' : Sidebars['OrderPoints'],
  '/orderpoints/ftp-batches' : Sidebars['OrderPoints'],
  '/orderpoints/shippingcost' : Sidebars['OrderPoints'],
  '/orderpoints/documents/reference' : Sidebars['OrderPoints'],
  '/orderpoints/documents/ftp-folders-send' : Sidebars['OrderPoints'],
  '/orderpoints/documents/ftp-folders-get' : Sidebars['OrderPoints'],
  '/orderpoints/help/1' : Sidebars['OrderPoints'],
  '/orderpoints/help/2' : Sidebars['OrderPoints'],
  '/orderpoints/help/3' : Sidebars['OrderPoints'],
  '/orderpoints/help/4' : Sidebars['OrderPoints'],
  '/orderpoints/help/5' : Sidebars['OrderPoints'],

  '/returntrak' : Sidebars['ReturnTrak'],
  '/returntrak/drafts' : Sidebars['ReturnTrak'],
  '/returntrak/shipped-orders' : Sidebars['ReturnTrak'],
  '/returntrak/rmas/open' : Sidebars['ReturnTrak'],
  '/returntrak/rmas/all' : Sidebars['ReturnTrak'],
  '/returntrak/rmas/items' : Sidebars['ReturnTrak'],
  '/returntrak/documents' : Sidebars['ReturnTrak'], // all 75
  '/returntrak/documents/return' : Sidebars['ReturnTrak'],
  '/returntrak/documents/reference' : Sidebars['ReturnTrak'],

  '/edi/overview' : Sidebars['Edi'],
  '/edi/overview/customize-view' : Sidebars['Edi'],
  '/edi/form' : Sidebars['Edi'], // HIDDEN
  '/edi/documents/orders-to-resolve' : Sidebars['Edi'],
  '/edi/documents/orders-to-approve' : Sidebars['Edi'],
  '/edi/documents/orders-to-ship' : Sidebars['Edi'],
  '/edi/documents/order-history' : Sidebars['Edi'],
  '/edi/documents/asn-856' : Sidebars['Edi'],
  '/edi/documents/invoice-810' : Sidebars['Edi'],
  '/edi/documents/remittance-820' : Sidebars['Edi'],
  '/edi/documents/product-activity-852' : Sidebars['Edi'],
  '/edi/documents/planning-schedule-830' : Sidebars['Edi'],
  '/edi/trading-partners/tp-activity' : Sidebars['Edi'],
  '/edi/trading-partners/tp-items' : Sidebars['Edi'],
  '/edi/trading-partners/tp-addresses' : Sidebars['Edi'],
  '/edi/trading-partners/tp-d-ship-methods' : Sidebars['Edi'],
  '/edi/trading-partners/tp-status' : Sidebars['Edi'],
  '/edi/trading-partners/basic-profile' : Sidebars['Edi'],
  '/edi/trading-partners/invoicing-profile' : Sidebars['Edi'],
  '/edi/trading-partners/dcl-partners' : Sidebars['Edi'],
  '/edi/ext-shipments/shipment-entry': Sidebars['Edi'],
  '/edi/ext-shipments/drafts': Sidebars['Edi'],

  '/documents' : Sidebars['Documents'],
  '/documents/general/approvals' : Sidebars['Documents'],
  '/documents/general/assembly' : Sidebars['Documents'],
  '/documents/general/bill' : Sidebars['Documents'],
  '/documents/general/consigned' : Sidebars['Documents'],
  '/documents/general/dangerousgoods' : Sidebars['Documents'],
  '/documents/general/general' : Sidebars['Documents'],
  '/documents/general/labels' : Sidebars['Documents'],
  '/documents/general/purchase' : Sidebars['Documents'],
  '/documents/general/etags' : Sidebars['Documents'],
  '/documents/general/return' : Sidebars['Documents'],
  '/documents/general/routing' : Sidebars['Documents'],
  '/documents/general/serial' : Sidebars['Documents'],
  '/documents/reference' : Sidebars['Documents'],
  '/ftp-folders/send' : Sidebars['Documents'],
  '/ftp-folders/get' : Sidebars['Documents'],
  '/special-docs/token-incoming-po' : Sidebars['Documents'],
  '/special-docs/token-incoming-sn' : Sidebars['Documents'],
  '/special-docs/token-sn-binding' : Sidebars['Documents'],
  '/special-docs/token-sn-unbinding' : Sidebars['Documents'],
  '/special-docs/token-cycle-count-info' : Sidebars['Documents'],

  '/services/administration-tasks/accounts' : Sidebars['Services'],
  '/services/administration-tasks/orderpoints-settings' : Sidebars['Services'],
  '/services/administration-tasks/returntrak-settings' : Sidebars['Services'],
  '/services/administration-tasks/special-settings' : Sidebars['Services'],
  '/services/administration-tasks/email-notifications/ship-confirmation' : Sidebars['Services'],
  '/services/administration-tasks/email-notifications/order-receipt' : Sidebars['Services'],
  '/services/administration-tasks/email-notifications/po-receipt' : Sidebars['Services'],
  '/services/administration-tasks/email-notifications/rma-receipt' : Sidebars['Services'],
  '/services/administration-tasks/email-notifications/unplanned-receipt' : Sidebars['Services'],
  '/services/administration-tasks/invoices/open' : Sidebars['Services'],
  '/services/administration-tasks/invoices/all' : Sidebars['Services'],

  '/services/administration-tasks/invoices/freight-charges' : Sidebars['Services'],
  '/services/administration-tasks/invoices/rate-cards' : Sidebars['Services'],

  '/transportation/analyzer': Sidebars['Transportation'],
  '/transportation/time': Sidebars['Transportation'],
  '/transportation/service': Sidebars['Transportation'],
  '/transportation/packages/shipping-detail': Sidebars['Transportation'],
  '/transportation/packages/cost-estimator': Sidebars['Transportation'],
}

const getSidebarForPathname = (pathname) => {
  if (pathname.includes('/view/')) {
    const index = pathname.indexOf('/view/')
    pathname = pathname.slice(0, index)
  }
  if (pathname.includes('/manage-filters')) {
    const index = pathname.indexOf('/manage-filters')
    pathname = pathname.slice(0, index)
  }
  const Sidebar = sidebarsConfig[pathname]
  return Sidebar ? <Sidebar /> : null

}

export default getSidebarForPathname
