const divisions = {
	DV01 : [ 'A', 'B', 'C', 'D', 'E' ],
	DV02 : [ 'A2', 'B2', 'C', 'D', 'E' ],
	DV03 : [ 'A','F','B2', 'E', 'G', 'C', 'D' ],
	DV04 : [ 'A2','H','B3', 'C', 'D', 'E' ],
	DV05 : [ 'A2','J','B2', 'C', 'E', 'G' ],
	DV06 : [ 'A2','K','B2', 'C', 'E', 'G' ],
	DV07 : [ 'M' ],
  DV08 : [ 'N' ],
  DV09 : [ 'N1' ],
	DV21 : [ 'P' ],
	DV22 : [ 'Q' ],
	DV23 : [ 'R' ],
	DV24 : [ 'S' ],
	DV25 : [ 'T' ],
	DV26 : [ 'V' ],
	DV27 : [ 'U' ],
	DV28 : [ 'W' ],
	DV29 : [ 'X' ],
	DV30 : [ 'Y' ],
	DV31 : [ 'Z' ],
	DV32 : [ 'S2' ],
  DV33 : [ 'CYC' ],
  DV34 : [ 'RMA','RMACFS', 'B', 'C', 'D'],
	DV35 : [ 'RMA','RMACFS', 'B', 'C', 'D'],
	DV36 : [ 'RMA','RMAAUTHITEMS','RMASHIPITEMS','RMACFS', 'B', 'C', 'D'],
  DV37 : [ 'DG' ],
  DV22A: [ 'Q2' ],
  DV206: [ 'BA' ],

	EDI1 : [ 'ORDER_INFO','PARTNER_INFO','STATUS_INFO','SHIPBILL_INFO'],
	EDI2 : [ 'ASN_ORDER_INFO','ASN_PARTNER_INFO'],
	EDI3 : [ 'INVOICE_ORDER_INFO','INVOICE_PARTNER_INFO'],
	EDI4 : [ 'REMITTANCE_INFO','REMITTANCE_PAYMENT_INFO' ],
	EDI5 : [ 'PRODUCT_ACTIVITY','PRODUCT_ACTIVITY_AMOUNTS' ],
	EDI6 : [ 'PLANNING_SCHEDULE' ],
	EDI7 : [ 'TP_ACTIVITY' ],
	EDI8 : [ 'TP_ITEMS' ],
	EDI9 : [ 'TP_ADDRESSES' ],
	EDI10 : [ 'SHIP_METHODS' ],

	EDI11 : [ 'TP_STATUS' ],
	EDI12 : [ 'BASIC_PROFILE' ],
	EDI13 : [ 'INVOICING_PROFILE' ],
	EDI14 : [ 'DCL_PARTNERS' ],
}

const config = {
	'/orders/open' : divisions[ 'DV01' ],
	'/orders/onhold' : divisions[ 'DV01' ],
	'/orders/backorders' : divisions[ 'DV01' ],
	'/orders/prerelease' : divisions[ 'DV01' ],
	'/orders/canceled' : divisions[ 'DV01' ],
	'/orders/shipped' : divisions[ 'DV02' ],
	'/orders/all' : divisions[ 'DV02' ],

	'/order-lines/open' : divisions[ 'DV03' ],
	'/order-lines/onhold' : divisions[ 'DV03' ],
	'/order-lines/backorders' : divisions[ 'DV03' ],
	'/order-lines/prerelease' : divisions[ 'DV03' ],
	'/order-lines/canceled' : divisions[ 'DV03' ],
	'/order-lines/shipped' : divisions[ 'DV03' ],
	'/order-lines/all' : divisions[ 'DV03' ],

	'/order-items/backlog' : divisions[ 'DV07' ],
    '/order-items/shipped' : divisions[ 'DV08' ],
    '/order-items/all' : divisions[ 'DV09' ],

	'/detail/item' : divisions[ 'DV03' ],
	'/detail/freight' : divisions[ 'DV04' ],
	'/transportation/packages/shipping-detail' : divisions[ 'DV04' ],

	'/detail/package' : divisions[ 'DV05' ],
	'/detail/serial' : divisions[ 'DV06' ],


	'/inventory/items/status' : divisions[ 'DV21' ],
	//'/inventory/items/received' : divisions[ 'DV22' ],
	'/inventory/items/receiving' : divisions[ 'DV22A' ],
	'/inventory/items/onhold' : divisions[ 'DV23' ],
	'/inventory/items/transactions' : divisions[ 'DV24' ],
	//'/inventory/items/toreceive' : divisions[ 'DV25' ],
	'/inventory/items/lotmaster' : divisions[ 'DV26' ],
	'/inventory/items/asofadate' : divisions[ 'DV27' ],
	'/inventory/planning/replenishment' : divisions[ 'DV28' ],
	'/inventory/planning/slowmoving' : divisions[ 'DV29' ],
	'/inventory/assembly' : divisions[ 'DV30' ],
	'/inventory/returns' : divisions[ 'DV31' ],
	'/inventory/items/trsummary' : divisions[ 'DV32' ],
  '/inventory/items/cyclecount' : divisions[ 'DV33' ],
  '/inventory/items/dg-data' : divisions[ 'DV37' ],
  '/inventory/items/bundle' : divisions[ 'DV206' ],

	'/returntrak/shipped-orders' : divisions[ 'DV01' ],

	'/returntrak/rmas/open' : divisions[ 'DV34' ],
	'/returntrak/rmas/all' : divisions[ 'DV35' ],
	'/returntrak/rmas/items' : divisions[ 'DV36' ],

	'/edi/documents/orders-to-resolve' : divisions[ 'EDI1' ],
	'/edi/documents/orders-to-approve' : divisions[ 'EDI1' ],
	'/edi/documents/orders-to-ship' : divisions[ 'EDI1' ],
	'/edi/documents/order-history' : divisions[ 'EDI1' ],
	'/edi/documents/asn-856' : divisions[ 'EDI2' ],
	'/edi/documents/invoice-810' : divisions[ 'EDI3' ],
	'/edi/documents/remittance-820' : divisions[ 'EDI4' ],
	'/edi/documents/product-activity-852' : divisions[ 'EDI5' ],
	'/edi/documents/planning-schedule-830' : divisions[ 'EDI6' ],
	'/edi/trading-partners/tp-activity' : divisions[ 'EDI7' ],
	'/edi/trading-partners/tp-items' : divisions[ 'EDI8' ],
	'/edi/trading-partners/tp-addresses' : divisions[ 'EDI9' ],
	'/edi/trading-partners/tp-d-ship-methods' : divisions[ 'EDI10' ],
	'/edi/trading-partners/tp-status' : divisions[ 'EDI11' ],
	'/edi/trading-partners/basic-profile' : divisions[ 'EDI12' ],
	'/edi/trading-partners/invoicing-profile' : divisions[ 'EDI13' ],
	'/edi/trading-partners/dcl-partners' : divisions[ 'EDI14' ],


}

export default config
